# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
          
      # Build 
      - name: "Build Android project"
        uses: vgaidarji/android-github-actions-build@v1.0.1
        with:
          args: "./gradlew assembleRelease"
     
      # Sign
      - name: Android Sign
        uses: Tlaster/android-sign@v1.2.2
        with:
          # The directory to find your release to sign
          releaseDirectory: "./release"
          # The key used to sign your release in base64 encoded format
          signingKeyBase64: "./keystore.jks"
          # The key alias
          alias: "filrougekeyalias"
          # The password to the keystore
          keyStorePassword: "aabbccddee"
          # The password for the key
          keyPassword: "aabbccddee"
