# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
          
      # Build 
      - uses: vgaidarji/android-github-actions-build@v1.0.1
        name: "Build Android project"
        with:
          args: "./gradlew assembleRelease"
          
      - name: Change Gradlew Permission
        run:
          chmod +x ./gradlew
          
      # Sign
      - uses: thomastvedt/sign-android-release@v2.2
        name: Sign Android release custom
        id: sign_app
        with:
          # The directory to find your release to sign
          releaseDirectory: app/build/outputs/apk/release
          # The key used to sign your release in base64 encoded format
          signingKeyBase64: ${{ secrets.AND_FILROUGE_SIGNING_KEY_BASE64 }}
          # The key alias
          alias: ${{ secrets.AND_FILROUGE_SIGNING_KEY_ALIAS }}
          # The password to the keystore
          keyStorePassword: ${{ secrets.AND_FILROUGE_SIGNING_STORE_PASSWORD }}
          # The password for the key
          keyPassword: ${{ secrets.AND_FILROUGE_SIGNING_KEY_PASSWORD }}
      
      # Upload
      - uses: actions/upload-artifact@v2
        name: Upload artifact
        with:  
          path: ${{steps.sign_app.outputs.signedReleaseFile}} 
